# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest



steps:

# Plan Stage #

- task: TerraformInstaller@1
  displayName: "Install Terraform"
  inputs:
    terraformVersion: 'latest'

# Terraform Init (Dev)


# Terraform Validate
         

    
# Terraform Plan (Dev)


